language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.8-dev"

install:
  - pip install coveralls
  - pip install -r requirements.txt

script:
  - nosetests --with-coverage --cover-package=blendplot
  - pip install ./
  - blendplot test/resources/data_01.csv data.obj a b c

after_success:
  - coveralls
